Styling update Manifesto
alkem-io/website pull request #312
Opened 2022-08-11 10:21 UTC by Roseghost

Styling updated to Birgit's feedback

### Describe the background of your pull request

Adjust padding and styling. 
+ Fontsize is different on this page 

### Additional context

Add any other context

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/alkem-io/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/alkem-io/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/alkem-io/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

2022-08-11 12:32 UTC, BirgitAlkemio commented
Hoi, Wil je even kijken naar: 

- deze visual, de rechterkant lijkt een uitsnede. 

![image](https://user-images.githubusercontent.com/105271229/184132055-97e2b464-193b-49c9-b9c3-270526be3135.png)

- er zit nog een kleine witmarge tussen deze 2 blokken. 
![image](https://user-images.githubusercontent.com/105271229/184132604-56c4af4e-7f5f-4009-a991-00e6e0431fb8.png)

- wbt de kleuren van de achtergrond. Kan je de blauwe blokken lichter maken (meer % transparant maken). De kleur overheerst nu nog teveel tov foto en tekst. En de achter across all boundaries dezelfde kleur als achter living community?

2022-08-11 12:42 UTC, BirgitAlkemio requested changes
@Roseghost Ik heb nav kort gesprek met @techsmyth vanmorgen de mockup in canva aanpgepast nav deze requested changes. Ik heb voor de achtergrondkleuren van de blokken nu gebruikt (dit zijn kleuren uit de afbeeldingen om het consistent te maken in de pagina layout) 
We cannot progress alone: #AFCBD6
Across all boundaries #F5F5F5
Open for all #FFFFFF 
Living community #DCEDF3
En de c2a button - join the community - in hetzelfde blok gezet als Alkemio Foundation Principles. De tekst van de principles heb ik dezelfde breedte gegeven als de visual + tekst samen in de blokken erboven en de titel ook links uitgelijnd. 
Laat me weten als het onduidelijk is. 

https://alkemio.my.canva.site/
943813

2022-08-11 14:00 UTC, larssondenise commented
@Roseghost

2022-08-24 05:31 UTC, techsmyth requested changes
The display of the manifesto now on a mobile has regressed with this update. It is likely that we need to keep the l-r setup. Lets discuss separately.

![image](https://user-images.githubusercontent.com/30729240/186336734-51f5ea4a-8548-4261-a1e9-26d6a3d3c49e.png)

2022-09-19 18:37 UTC, BirgitAlkemio commented
@techsmyth - Can you help @Roseghost  to get this one through the pipeline?  
If I look at the preview on my mobile and tablet, the images are full width and adaptive, if I resize my window on my desktop it does not resize the text blocks in ratio with the images. Shall we create a new issue for this and close this one?

2022-09-20 08:56 UTC, techsmyth approved these changes
Nice update!

2022-09-20 08:57 UTC, merged